name = "resumaker-next"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

pages_build_output_dir = ".next"

[env.production]
name = "resumaker-next"
workers_dev = true 