/**
 * Dynamically registers the Symbola emoji font so jsPDF's html() renderer
 * can embed it when needed.
 *
 * Expects /public/fonts/Symbola-normal.js to exist (generated by the
 * jsPDF font-converter).
 */
export async function registerEmojiFont() {
  // Executes the UMD wrapper inside Symbola-normal.js, which calls
  // jsPDF.addFileToVFS() + addFont().
  await import("/fonts/Symbola-normal.js");
} 