/**
 * Dynamically registers the Symbola emoji font so jsPDF's html() renderer
 * can embed it when needed.
 *
 * Expects /public/fonts/Symbola-normal.js to exist (generated by the
 * jsPDF font-converter).
 */
export async function registerEmojiFont() {
  try {
    // Executes the UMD wrapper inside Symbola-normal.js, which calls
    // jsPDF.addFileToVFS() + addFont().
    await import("/fonts/Symbola-normal.js");
    console.log("✅ Symbola emoji font loaded successfully");
  } catch (error) {
    console.warn("⚠️ Symbola emoji font not found, using fallback fonts");
    // Continue without the emoji font - jsPDF will use fallback fonts
  }
} 